import {useEffect,useRef} from "react";
import {Link,NavLink} from "react-router-dom";
import {Heart,MapPin,Menu,Search,ShoppingBag,X} from "lucide-react";
import {store} from "../data/catalog";
export const links=[{name:"Каталог",to:"/catalog"},{name:"Новинки",to:"/catalog/new"},{name:"WH Collection",to:"/catalog/collection"},{name:"Акции",to:"/catalog/promo"}];
export type Info="store"|"delivery"|"size";
export default function Header({count,favorites,searchOpen,onSearch,onCart,onMenu,onInfo,query,onQuery,resultCount}:{count:number;favorites:number;searchOpen:boolean;onSearch:()=>void;onCart:()=>void;onMenu:()=>void;onInfo:(info:Info)=>void;query:string;onQuery:(q:string)=>void;resultCount:number}){
const input=useRef<HTMLInputElement>(null);useEffect(()=>{if(searchOpen)input.current?.focus();},[searchOpen]);
return <><div className="utility-bar"><a href={store.maps} target="_blank" rel="noreferrer"><MapPin size={13}/>Каспийск, Ленина, 39А</a><span>Женская одежда · WH Collection</span><button onClick={()=>onInfo("store")}>Ежедневно 09:00–22:00</button></div><header className="site-header"><div className="header-main"><div className="header-left"><button className="icon-button mobile-menu" aria-label="Открыть меню" onClick={onMenu}><Menu/></button><a className="header-store" href={store.maps} target="_blank" rel="noreferrer"><MapPin size={18}/><span>Наш магазин<br/><small>Каспийск</small></span></a></div><Link to="/" className="wordmark" aria-label="White House — главная">WHITE HOUSE<span>ЖЕНСКАЯ ОДЕЖДА</span></Link><div className="header-actions"><button className="icon-button" aria-label="Поиск по каталогу" aria-expanded={searchOpen} onClick={onSearch}>{searchOpen?<X/>:<Search/>}</button><Link to="/favorites" className="icon-button favorite-nav" aria-label={"Избранное, "+favorites}><Heart/>{favorites>0&&<b>{favorites}</b>}</Link><button className="icon-button" aria-label={"Корзина, "+count+" товаров"} onClick={onCart}><ShoppingBag/>{count>0&&<b>{count}</b>}</button></div></div><nav className="main-nav" aria-label="Основная навигация">{links.map(l=><NavLink end key={l.to} to={l.to}>{l.name}</NavLink>)}<button onClick={()=>onInfo("delivery")}>Доставка и примерка</button><button onClick={()=>onInfo("store")}>Контакты</button></nav>{searchOpen&&<div className="search-area"><Search size={22}/><input ref={input} type="search" value={query} onChange={e=>onQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Escape")onSearch();if(e.key==="Enter")document.getElementById("catalog")?.scrollIntoView({behavior:"smooth"});}} placeholder="Найти платье, костюм или цвет" aria-label="Найти в каталоге" maxLength={150}/><span>{resultCount} моделей</span></div>}</header></>;
}
