import {useState} from "react";
import {Heart,MessageCircle,ShoppingBag} from "lucide-react";
import {colors,money,productSizes,discountPercent,whatsappUrl,type Product} from "../data/catalog";
import ProductGallery from "./ProductGallery";
import type {CartLine} from "../lib/cart";
export default function ProductDetails({product:p,saved,onFavorite,onAdd}:{product:Product;saved:boolean;onFavorite:(id:string)=>void;onAdd:(line:CartLine)=>void}){
const [size,setSize]=useState("");const [color,setColor]=useState(p.colors.length===1?p.colors[0]:"");const [error,setError]=useState(false);
const unavailable=p.availability==="out-of-stock";
function add(){if(unavailable||p.unavailableSizes?.includes(size))return;if(!size){setError(true);return;}onAdd({id:p.id,size,color:color||"Уточнить цвет",quantity:1});}
const question="Добрый день. Интересует «"+p.name+"». "+(size?"Желаемый размер: "+size+". ":"")+(color?"Цвет: "+color+". ":"")+"Подскажите, пожалуйста, наличие и актуальную цену.";
return <div className={"product-detail "+(unavailable?"product-detail--out":"")}><ProductGallery product={p}/><div className="detail-content"><span className="eyebrow">{p.collection?"WH COLLECTION":"WHITE HOUSE"}</span><div className="detail-price">{p.price===null?"Цена по запросу":money(p.price)}{!!discountPercent(p)&&<><del>{money(p.oldPrice!)}</del><span className="discount-tag">−{discountPercent(p)}%</span></>}</div><p className="detail-description">{p.description}</p><p className="availability-note">{unavailable?"Сейчас этой модели нет в наличии. Уточните у консультанта ожидаемое поступление.":"Наличие, размеры и актуальную цену подтвердит консультант."}</p><fieldset className="size-selector"><legend>{p.sizes?.length?"Размер":"Желаемый размер"}</legend><div>{productSizes(p).map(s=><button disabled={unavailable||p.unavailableSizes?.includes(s)} key={s} aria-pressed={size===s} onClick={()=>{setSize(s);setError(false);}}>{s}</button>)}</div>{error&&<p role="alert" className="size-error">Выберите размер или «Подобрать размер».</p>}</fieldset>{p.colors.length>1&&<label className="detail-color">Желаемый цвет<select disabled={unavailable} aria-label="Желаемый цвет" value={color} onChange={e=>setColor(e.target.value)}><option value="">Уточнить у консультанта</option>{p.colors.map(c=><option value={c} key={c}>{c}</option>)}</select></label>}{p.colors.length===1&&<p className="detail-color-label"><i style={{background:colors[p.colors[0]]}}/>На фото: {p.colors[0].toLowerCase()}</p>}<div className="detail-buttons"><button className="dark-button" disabled={unavailable} onClick={add}>{unavailable?"Нет в наличии":"Добавить в корзину"}<ShoppingBag size={18}/></button><button className="detail-save" onClick={()=>onFavorite(p.id)} aria-pressed={saved} aria-label="Сохранить товар в избранное"><Heart size={21} fill={saved?"currentColor":"none"}/></button></div><a className="direct-question" href={whatsappUrl(question)} target="_blank" rel="noreferrer">Уточнить в WhatsApp<MessageCircle size={17}/></a><div className="product-facts">{p.material&&<details open><summary>Состав и уход</summary><p>{p.material}</p></details>}{p.measurements&&<details><summary>Замеры и посадка</summary><p>{p.measurements}</p></details>}{p.modelInfo&&<details><summary>На модели</summary><p>{p.modelInfo}</p></details>}</div></div></div>;
}
