import {useEffect,useRef,useState,type FormEvent} from "react";
import {Link} from "react-router-dom";
import {ArrowLeft,Check,Eye,EyeOff,LogOut,Pencil,RefreshCw,Trash2} from "lucide-react";
import {money,type Product} from "../data/catalog";
import {assetUrl} from "../lib/assetUrl";
import type {CatalogData,Promotion,StoreContent} from "../../shared/catalog";
import {catalogChanged,loadCatalog,saveCatalog} from "./api";
import {finishPassword,getSession,processCallback,recoverPassword,signIn,signOut,type PasswordFlow,type Session} from "./auth";
import ProductEditor from "./ProductEditor";
import PromotionEditor from "./PromotionEditor";
import "./admin.css";

export default function AdminPanel(){
  const [session,setSession]=useState<Session|null>(null),[flow,setFlow]=useState<PasswordFlow>(null),[data,setData]=useState<CatalogData|null>(null);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[passwordAgain,setPasswordAgain]=useState("");
  const [product,setProduct]=useState<Product>(),[promotion,setPromotion]=useState<Promotion>(),[productKey,setProductKey]=useState(0),[promotionKey,setPromotionKey]=useState(0);
  const [tab,setTab]=useState<"products"|"promotions"|"content">("products");const locked=useRef(false);
  const message=(reason:unknown)=>setError(reason instanceof Error?reason.message:"Не удалось выполнить действие");
  useEffect(()=>{let active=true;async function init(){try{const initial=await getSession();const callback=await processCallback(initial.provider);const current=await getSession();if(active){setSession(current);setFlow(callback);if(current.user)setData(await loadCatalog());}}catch(reason){if(active)message(reason);}finally{if(active)setLoading(false);}}void init();return()=>{active=false;};},[]);
  const run=async(action:()=>Promise<void>)=>{if(locked.current)return;locked.current=true;setBusy(true);setError("");setNotice("");try{await action();}catch(reason){message(reason);}finally{locked.current=false;setBusy(false);}};
  const login=async(event:FormEvent)=>{event.preventDefault();await run(async()=>{if(!session)throw new Error("Сервер управления недоступен");const next=flow?await finishPassword(flow,password):await signIn(session.provider,email.trim(),password);if(!next.user){await signOut(next.provider);throw new Error("Эта учётная запись не назначена администратором");}setPassword("");setPasswordAgain("");setSession(next);setFlow(null);setData(await loadCatalog());});};
  const logout=()=>run(async()=>{if(session)await signOut(session.provider);setSession(s=>s?{...s,user:null}:null);setData(null);setProduct(undefined);setPromotion(undefined);});
  const refresh=()=>run(async()=>{const next=await getSession();setSession(next);setData(next.user?await loadCatalog():null);});
  const mutate=async(next:CatalogData)=>{if(locked.current)return false;let saved=false;await run(async()=>{setData(await saveCatalog(next));catalogChanged();setNotice("Изменения сохранены");saved=true;});return saved;};
  const resetProduct=()=>{setProduct(undefined);setProductKey(k=>k+1);};const resetPromotion=()=>{setPromotion(undefined);setPromotionKey(k=>k+1);};
  const saveProduct=async(next:Product)=>{if(!data)return false;const exists=data.products.some(p=>p.id===next.id);const ok=await mutate({...data,products:exists?data.products.map(p=>p.id===next.id?next:p):[...data.products,next]});if(ok)resetProduct();return ok;};
  const savePromotion=async(next:Promotion)=>{if(!data)return false;const exists=data.promotions.some(p=>p.id===next.id);const ok=await mutate({...data,promotions:exists?data.promotions.map(p=>p.id===next.id?next:p):[...data.promotions,next]});if(ok)resetPromotion();return ok;};
  const removeProduct=async(p:Product)=>{if(!data||!window.confirm(`Удалить «${p.name}»? Карточка исчезнет с сайта.`))return;if(await mutate({...data,products:data.products.filter(item=>item.id!==p.id)})&&product?.id===p.id)resetProduct();};
  const removePromotion=async(p:Promotion)=>{if(!data||!window.confirm(`Удалить предложение «${p.title}»?`))return;if(await mutate({...data,promotions:data.promotions.filter(item=>item.id!==p.id)})&&promotion?.id===p.id)resetPromotion();};
  const alerts=<>{error&&<p className="admin-error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status"><Check size={17}/>{notice}</p>}</>;
  if(loading)return <main className="admin-shell admin-wait" aria-busy="true">Проверяем доступ…</main>;
  if(!session?.user||flow)return <main className="admin-shell"><div className="admin-auth"><Link to="/" className="admin-back"><ArrowLeft size={16}/>Вернуться в магазин</Link><span className="eyebrow">WHITE HOUSE · УПРАВЛЕНИЕ</span><h1>{flow?"Задайте пароль":"Вход администратора"}</h1><p>Товары, фотографии и предложения магазина.</p>{alerts}<form onSubmit={login}><fieldset disabled={busy||!session} className="admin-fields">{!flow&&<label>E-mail<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}<label>Пароль<input type="password" autoComplete={flow?"new-password":"current-password"} required minLength={flow?12:undefined} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)}/></label>{flow&&<label>Повторите пароль<input type="password" autoComplete="new-password" required value={passwordAgain} onChange={e=>{setPasswordAgain(e.target.value);e.target.setCustomValidity(e.target.value===password?"":"Пароли не совпадают");}}/></label>}<button className="dark-button" disabled={!!flow&&password!==passwordAgain}>{busy?"Подождите…":flow?"Сохранить пароль":"Войти"}</button></fieldset></form>{!flow&&session?.provider==="netlify"&&<button className="text-button admin-recovery" disabled={busy} onClick={()=>void run(async()=>{if(!email.trim())throw new Error("Сначала укажите e-mail");await recoverPassword(email.trim());setNotice("Если адрес зарегистрирован, на него придёт ссылка восстановления.");})}>Восстановить пароль</button>}{session?.provider==="server"&&<p className="admin-help">Если забыли пароль, обратитесь к владельцу сервера.</p>}{!session&&<button className="text-button" onClick={()=>window.location.reload()}>Повторить подключение</button>}</div></main>;
  return <div className="admin-shell"><header className="admin-top"><Link to="/" className="admin-brand">WHITE HOUSE<small>УПРАВЛЕНИЕ МАГАЗИНОМ</small></Link><div className="admin-user"><span>{session.user.email}</span><button aria-label="Выйти" disabled={busy} onClick={()=>void logout()}><LogOut size={20}/></button></div></header><main className="admin-main"><div className="admin-heading"><div><span className="eyebrow">WHITE HOUSE · КАСПИЙСК</span><h1>Ваш магазин</h1><p>Добавляйте модели и управляйте предложениями.</p></div><Link to="/catalog" className="text-link"><ArrowLeft size={16}/>Открыть каталог</Link></div>{alerts}<div className="admin-toolbar"><div className="admin-tabs" role="tablist" aria-label="Разделы управления">{([['products','Товары'],['promotions','Акции и бонусы'],['content','Тексты']] as const).map(([key,title])=><button role="tab" aria-selected={tab===key} key={key} onClick={()=>setTab(key)}>{title}</button>)}</div><button className="text-button" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={15}/>Обновить данные</button></div>
  {!data?<div className="admin-card"><p>Каталог пока не загружен.</p><button className="dark-button" disabled={busy} onClick={()=>void refresh()}>Загрузить каталог</button></div>:<>
    {tab==="products"&&<div className="admin-grid"><ProductEditor key={productKey} product={product} busy={busy} onSave={saveProduct} onCancel={resetProduct} onError={setError}/><section className="admin-card"><h2>Товары <span className="admin-muted">{data.products.length}</span></h2>{!data.products.length&&<p className="admin-muted">Добавьте первую карточку.</p>}<div className="admin-list">{data.products.map(p=><article className="admin-item" key={p.id}><img className={p.availability==="out-of-stock"?"is-out":""} src={assetUrl(p.image)} alt=""/><div className="admin-item-copy"><strong>{p.name}</strong><span>{p.price===null?"Цена по запросу":money(p.price)}</span><small>{p.hidden?"Скрыт с сайта":p.availability==="out-of-stock"?"Нет в наличии":"В наличии"}</small><div className="admin-item-actions"><button disabled={busy} onClick={()=>{setProduct(p);setProductKey(k=>k+1);window.scrollTo({top:0,behavior:"smooth"});}}><Pencil size={14}/>Изменить</button><button disabled={busy} onClick={()=>void mutate({...data,products:data.products.map(item=>item.id===p.id?{...item,availability:p.availability==="out-of-stock"?"in-stock":"out-of-stock"}:item)})}>{p.availability==="out-of-stock"?"Вернуть в наличие":"Нет в наличии"}</button><button disabled={busy} onClick={()=>void mutate({...data,products:data.products.map(item=>item.id===p.id?{...item,hidden:!p.hidden}:item)})}>{p.hidden?<Eye size={14}/>:<EyeOff size={14}/>} {p.hidden?"Показать":"Скрыть"}</button><button className="danger" disabled={busy} onClick={()=>void removeProduct(p)}><Trash2 size={14}/>Удалить</button></div></div></article>)}</div></section></div>}
    {tab==="promotions"&&<div className="admin-grid"><PromotionEditor key={promotionKey} promotion={promotion} busy={busy} onSave={savePromotion} onCancel={resetPromotion}/><section className="admin-card"><h2>Акции, скидки и бонусы</h2>{!data.promotions.length&&<p className="admin-muted">Здесь появятся ваши предложения.</p>}{data.promotions.map(p=><article className="admin-promo-item" key={p.id}><strong>{p.title}</strong><p>{p.value}</p><small>{p.active?"Показывается на сайте":"Скрыто"}</small><div className="admin-item-actions"><button disabled={busy} onClick={()=>{setPromotion(p);setPromotionKey(k=>k+1);}}>Изменить</button><button disabled={busy} onClick={()=>void mutate({...data,promotions:data.promotions.map(item=>item.id===p.id?{...item,active:!p.active}:item)})}>{p.active?"Скрыть":"Показать"}</button><button className="danger" disabled={busy} onClick={()=>void removePromotion(p)}>Удалить</button></div></article>)}</section></div>}
    {tab==="content"&&<ContentEditor key={data.revision} content={data.content} busy={busy} onSave={content=>mutate({...data,content})}/>}
  </>}</main></div>;
}
function ContentEditor({content,busy,onSave}:{content:StoreContent;busy:boolean;onSave:(content:StoreContent)=>Promise<boolean>}){
  const [draft,setDraft]=useState({...content});return <form className="admin-card admin-content" onSubmit={e=>{e.preventDefault();void onSave(draft);}}><h2>Страница акций</h2><fieldset className="admin-fields" disabled={busy}><label>Заголовок<input maxLength={160} value={draft.promoTitle} onChange={e=>setDraft({...draft,promoTitle:e.target.value})}/></label><label>Описание<textarea maxLength={1500} rows={4} value={draft.promoDescription} onChange={e=>setDraft({...draft,promoDescription:e.target.value})}/></label><label>Текст бонусов<textarea maxLength={1500} rows={3} value={draft.bonusText} onChange={e=>setDraft({...draft,bonusText:e.target.value})}/></label><button className="dark-button">{busy?"Сохраняем…":"Сохранить тексты"}</button></fieldset></form>;
}
