import {useState} from "react";
import {defaultContent,type BannerKey,type StoreContent} from "../../shared/catalog";
import {adminImageUrl,uploadPhoto} from "./api";
const names:Record<BannerKey,string>={home:"Главная",catalog:"Каталог",new:"Новинки",collection:"WH Collection",promo:"Акции"};
export default function ContentEditor({content,busy,onSave}:{content:StoreContent;busy:boolean;onSave:(content:StoreContent)=>Promise<boolean>}){
  const [draft,setDraft]=useState(()=>({...content,banners:structuredClone(content.banners??defaultContent.banners!)}));
  const [uploading,setUploading]=useState(false),[error,setError]=useState("");
  const banner=(key:BannerKey,patch:Partial<NonNullable<StoreContent["banners"]>[BannerKey]>)=>setDraft(d=>({...d,banners:{...d.banners,[key]:{...d.banners[key],...patch}}}));
  return <form className="admin-card admin-content" onSubmit={e=>{e.preventDefault();void onSave(draft);}}><h2>Оформление и контакты</h2>{error&&<p role="alert" className="admin-error">{error}</p>}<fieldset className="admin-fields" disabled={busy||uploading}>
    <label>Почта для заказов<input type="email" required maxLength={254} value={draft.orderEmail??defaultContent.orderEmail} onChange={e=>setDraft({...draft,orderEmail:e.target.value})}/></label><p className="admin-help">На этот адрес покупатель отправляет письмо с сайта. На своём сервере сюда же приходят автоматические уведомления после настройки SMTP.</p>
    {(Object.keys(names) as BannerKey[]).map(key=><details className="admin-banner-editor" key={key}><summary>Баннер · {names[key]}</summary><div className="admin-fields"><img src={adminImageUrl(draft.banners[key].image)} alt="Предпросмотр баннера"/><label>Заголовок<textarea rows={2} maxLength={100} required value={draft.banners[key].title} onChange={e=>banner(key,{title:e.target.value})}/></label><label>Подпись<input maxLength={160} value={draft.banners[key].caption} onChange={e=>banner(key,{caption:e.target.value})}/></label><label>Фотография<input required maxLength={1000} value={draft.banners[key].image} onChange={e=>banner(key,{image:e.target.value})}/></label><label>Загрузить фотографию<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;setUploading(true);setError("");try{const result=await uploadPhoto(file);banner(key,{image:result.url});}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить фото");}finally{setUploading(false);}}}/></label></div></details>)}
    <h3>Страница акций</h3><label>Заголовок<input maxLength={160} value={draft.promoTitle} onChange={e=>setDraft({...draft,promoTitle:e.target.value})}/></label><label>Описание<textarea maxLength={1500} rows={4} value={draft.promoDescription} onChange={e=>setDraft({...draft,promoDescription:e.target.value})}/></label><label>Текст бонусов<textarea maxLength={1500} rows={3} value={draft.bonusText} onChange={e=>setDraft({...draft,bonusText:e.target.value})}/></label><button className="dark-button">{busy?"Сохраняем…":"Сохранить оформление"}</button>
  </fieldset></form>;
}
