import {useEffect,useState} from "react";
import {RefreshCw,Mail} from "lucide-react";
import {request} from "./api";
import {orderStatuses,type OrderRecord,type MailStatus} from "../../shared/orders";
import {money} from "../data/catalog";
const mailLabels:Record<MailStatus,string>={queued:"Письмо в очереди",sending:"Письмо отправляется",sent:"Письмо отправлено",failed:"Не удалось отправить письмо",unconfigured:"Почта не подключена"};
export default function OrdersPanel(){
  const [orders,setOrders]=useState<OrderRecord[]>([]),[configured,setConfigured]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const refresh=async()=>{setLoading(true);try{const data=await request<{orders:OrderRecord[];mailConfigured:boolean}>("/api/admin/orders");setOrders(data.orders);setConfigured(data.mailConfigured);setError("");}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить заказы");}finally{setLoading(false);}};
  useEffect(()=>{void refresh();},[]);
  const update=async(action:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError("");try{await action();await refresh();}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить заказ");}finally{setBusy(false);}};
  return <section className="admin-orders"><div className="admin-card-heading"><h2>Заказы</h2><button disabled={loading||busy} className="text-button" onClick={()=>void refresh()}><RefreshCw size={15}/>Обновить заказы</button></div>{error&&<p role="alert" className="admin-error">{error}</p>}{!configured&&!loading&&<p className="admin-publish-note">Заказы сохраняются. Чтобы получать письма автоматически, настройте SMTP на сервере по инструкции docs/EMAIL_ORDERS.md.</p>}{loading&&<p role="status">Загружаем заказы…</p>}{!loading&&!orders.length&&<div className="admin-card"><h3>Здесь появятся новые заказы</h3><p>После оформления на сайте заявка сохраняется независимо от доставки письма.</p></div>}
  {orders.map(order=><article className="admin-card order-card" key={order.id}><header><div><h3>{order.number}</h3><span>{new Date(order.createdAt).toLocaleString("ru-RU")}</span></div><label>Статус<select aria-label={"Статус "+order.number} disabled={busy} value={order.status} onChange={e=>void update(()=>request("/api/admin/orders/"+order.id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:e.target.value,version:order.version})}))}>{Object.entries(orderStatuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></header><p><strong>{order.customer.name}</strong> · <a href={"tel:"+order.customer.phone.replace(/[^+\d]/g,"")}>{order.customer.phone}</a></p><p>{order.customer.delivery==="pickup"?"Самовывоз из магазина":"Доставка: "+order.customer.address}</p>{order.customer.comment&&<p className="order-comment">{order.customer.comment}</p>}<ul>{order.items.map((item,i)=><li key={i}><div>{item.name}<small>{item.size} · {item.color} · {item.quantity} шт.</small></div><strong>{item.unitPrice===null?"Уточнить цену":money(item.unitPrice*item.quantity)}</strong></li>)}</ul><p className="order-amount">{order.unknown?"Известная стоимость":"Стоимость товаров"}<strong>{money(order.amount)}</strong></p><div className="order-mail"><span><Mail size={15}/>{mailLabels[order.mailStatus]}</span>{configured&&["failed","unconfigured"].includes(order.mailStatus)&&<button className="text-button" disabled={busy} onClick={()=>void update(()=>request("/api/admin/orders/"+order.id+"/retry-mail",{method:"POST"}))}>Повторить отправку</button>}</div></article>)}{orders.length===100&&<p className="admin-help">Показаны последние 100 заказов.</p>}</section>;
}
